"""create tables

Revision ID: e4c81ea92c4a
Revises: e5549ff27a6d
Create Date: 2025-04-07 13:55:38.562735

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e4c81ea92c4a"
down_revision: Union[str, None] = "e5549ff27a6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE events
        SET message_id = 0
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE my_table
        SET new_column = NULL
        """
    )
    # ### end Alembic commands ###
